import {
  FaHome,
  FaBook,
  FaClipboardList,
  FaCalendarAlt,
  FaBookReader,
  FaStore,
  FaSearchLocation,
  FaBookOpen,
  FaPoll,
  FaComments,
  FaBell,
  FaCog,
  FaUsers,
  FaUserGraduate,
  FaChartBar,
  FaLayerGroup,
  FaFileAlt,
  FaCheckCircle,
  FaBullhorn,
  FaUpload,
  FaExclamationTriangle,
  FaRobot,
} from "react-icons/fa";

export const navigation = {
  student: [
    { title: "Dashboard", path: "/student/dashboard", icon: FaHome },
    { title: "Courses", path: "/student/courses", icon: FaBook },
    { title: "Units", path: "/student/units", icon: FaLayerGroup },
    { title: "Notes", path: "/student/notes", icon: FaFileAlt },
    { title: "Assignments", path: "/student/assignments", icon: FaClipboardList },
    { title: "Timetable", path: "/student/timetable", icon: FaCalendarAlt },
    { title: "Attendance", path: "/student/attendance", icon: FaCheckCircle },
    { title: "Results", path: "/student/results", icon: FaChartBar },
    { title: "My Reports", path: "/student/my-reports", icon: FaExclamationTriangle },
    { title: "AI Assistant", path: "/ai-assistant", icon: FaRobot },
    { title: "Feed", path: "/feed", icon: FaBookReader },
    { title: "Marketplace", path: "/marketplace", icon: FaStore },
    { title: "Lost & Found", path: "/lost-and-found", icon: FaSearchLocation },
    { title: "Library", path: "/library", icon: FaBookOpen },
    { title: "Study Groups", path: "/study-groups", icon: FaUsers },
    { title: "Polls", path: "/polls", icon: FaPoll },
    { title: "Clubs", path: "/clubs", icon: FaUsers },
    { title: "Messages", path: "/messages", icon: FaComments },
    { title: "Settings", path: "/settings", icon: FaCog },
  ],
  lecturer: [
    { title: "Dashboard", path: "/lecturer/dashboard", icon: FaHome },
    { title: "My Courses", path: "/lecturer/courses", icon: FaBook },
    { title: "Upload Notes", path: "/lecturer/upload-notes", icon: FaUpload },
    { title: "Exams", path: "/lecturer/exams", icon: FaClipboardList },
    { title: "Submissions", path: "/lecturer/submissions", icon: FaUserGraduate },
    { title: "Emergency Reports", path: "/lecturer/emergency-reports", icon: FaExclamationTriangle },
    { title: "AI Assistant", path: "/ai-assistant", icon: FaRobot },
    { title: "Announcements", path: "/lecturer/announcements", icon: FaBullhorn },
    { title: "Analytics", path: "/lecturer/analytics", icon: FaChartBar },
    { title: "Messages", path: "/messages", icon: FaComments },
    { title: "Settings", path: "/settings", icon: FaCog },
  ],
  admin: [
    { title: "Dashboard", path: "/admin/dashboard", icon: FaHome },
    { title: "Users", path: "/admin/users", icon: FaUsers },
    { title: "Notifications", path: "/notifications", icon: FaBell },
    { title: "Analytics", path: "/lecturer/analytics", icon: FaChartBar },
    { title: "Settings", path: "/settings", icon: FaCog },
  ],
};
